server:
  port: 8980
spring:
  application:
    name: rapid-demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(IOM37WbNYqAQtn04+3QoAw==)
    password: ENC(7XUyH/sfCP4WRLoRBOWwJkB1PvHhWwZzBFT50eaeuHM=)
    url: jdbc:mysql://niescloud-mysql:3336/niescloud_opm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  redis:
    host: niescloud-redis
    port: 5379
    password: NIESCloud2020
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
TimeConfig:
  corn: 0 0/25 * * * ?
  account_scan_switch: true
#加解密根密码
jasypt:
  encryptor:
    #加密盐
    password: upbest@2019
    #默认加密算法
    algorithm: PBEWithMD5AndDES